version: "3"
services:
  front:
    container_name: frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/src:/usr/src/app/src
    env_file:
      - ./front/.env
    ports:
      - 3000:3000
    restart: always
  back:
    container_name: backend
    depends_on:
      - db
      - mongo
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - ./back/.env
    ports:
      - 5000:5000
    restart: always
  db:
    container_name: mysql
    # image: mysql:latest
    platform: linux/x86_64
    image : library/mysql:latest
    env_file:
      - ./db/.env
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
  mongo:
    container_name: mongo
    image: mongo
    env_file:
      - ./db/.env
    volumes:
      - ./db/mongo:/data/db
    ports:
      - 27017-27019:27017-27019
    restart: always
