version: "3"
services:
  front:
    container_name: frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file:
      - ./front/.env
    ports:
      - 3000:3000
    restart: always
  back:
    container_name: backend
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - ./back/.env
    ports:
      - 5000:5000
    restart: always
  db:
    container_name: database
    image: mysql:latest
    env_file:
      - ./db/.env
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
