name: CI

on:
  pull_request:
    branches: [ deploy-frontend ]
    types: [ closed ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: get source
      uses: actions/checkout@v2
    - name: list of files
      run: cd front && ls
    - name: list of filess
      run: ls
