name: CI

on:
  pull_request:
    branches: [ deploy-frontend ]
    types: [ closed ]
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list of files
        working-directory: front
        run: ls
